### PR TITLE
Use codegen models

### PR DESCRIPTION
**Pull request by mnida**

### CODE REVIEW

**Review by mnida — COMMENTED** [review]
Anything left here @glamboyosa ? I'll add in the addon functions as well.

**Comment by mnida** [comment]
Looks like the auto tests are deploying well

**Comment by mnida** [comment]
@glamboyosa Are these tests passing locally?

**Comment by glamboyosa** [comment]
tests fail but imo that's expected. they require an API key in an .env file.

**Comment by glamboyosa** [comment]
Everything is good to go. Pull locally and test the bump script. via 
```
npm run update-types -- patch
```

or whatever version.

**Comment by mnida** [comment]
Nice

**Pull request merged**
